#169947 WhatsApp contact
SkillsFundingAgency/dss-contact pull request #56
Opened 2024-06-07 13:43 UTC by JoeHS-edu

2024-06-10 10:43 UTC, abu-khubaib approved these changes

2024-07-16 10:24 UTC, bmatthews-DFE requested changes
If you are updating DSS APIs, we need to update and release a new version of the [Service Responsibilities Document](https://skillsfundingagency.atlassian.net/wiki/spaces/DFC/pages/1466237428/DSS+documents+issued+to+Prime+Contractors)

2024-07-17 08:52 UTC, bmatthews-DFE requested changes
No unit tests present

2024-07-22 14:13 UTC, Lovre-Schonauer approved these changes

2024-07-25 10:36 UTC, closed without merging